<?php
//$this->headMeta()->appendHttpEquiv('Content-Type','text/html;charset=utf-8');
//$this->headTitle()->setSeparator(' :: ');
//$this->headTitle('ITSTE');
echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . "/css/menu.css"); ?>
    </head>
    <body>
        <div id="wrap">
        <div id="banner">
        </div>

        <div class="topnav">
            <?php //echo $this->navigation()->menu(); ?>
        </div>
        <div class="breadcrums">
            <?php
                /*echo $this->navigation()
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setLinkLast(true)
                        ->setSeparator(' : ');*/
            ?>
        </div>

        <div id="contenido">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content; ?>
	</div>

        <div id="footer"><a href="#">George Mc Jackson 2010</a>
        </div>

    </div>
    </body>
</html>