<?php
echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . "/css/reset.css"); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . "/css/text.css"); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . "/css/960.css"); ?>
        <?= $this->headLink()->prependStylesheet($this->baseUrl() . "/css/scitec_style.css" ); ?>
        
    </head>
    <body>
        <div class="container_12" id="banner">
            <div class="grid_10" id="logo"></div>
            <div class="grid_2" id="gob"></div>

            <div class="clear"></div>
        </div>
        
        <div class="container_12" id="wrapper">
            <div class="grid_12" id="topnav"><?php echo $this->navigation()->menu()->setAcl($this->acl); ?></div>

            <div class="clear"></div>
            
            <div class="grid_10 prefix_2" id="content">
                <!--Contenido-->
                <div id="breadcrumb"><?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?><br></div>
				<div id="contenido">
					<?php echo $this->layout()->content; ?>
				</div>
            </div>

            <div class="clear"></div>
        </div>

		<div id="footer">
        	<p>Tema creado por: <a href="http://www.wordpress.com/georgemcjackson">GMJ</a><br>
			Licencia Libre
			</p>
        </div>

    </body>
</html>